// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHLCn8qaDl6J2tjwN4jJoFNqlm-L2zXCU',
    appId: '1:497886634309:android:d3c8b2ebc453ca46bfde2c',
    messagingSenderId: '497886634309',
    projectId: 'cscc-app-13e55',
    storageBucket: 'cscc-app-13e55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFXUKooQ7FjNwU068eAw7co_3IJqR4D6g',
    appId: '1:497886634309:ios:a08c079f2132a242bfde2c',
    messagingSenderId: '497886634309',
    projectId: 'cscc-app-13e55',
    storageBucket: 'cscc-app-13e55.firebasestorage.app',
    iosBundleId: 'com.example.csccApp',
  );
}